name: cloudstream
description: A Flutter project for watching movies and tv shows.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  movie_provider:
    path: ./package/movie_provider
  shimmer: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  disk_space: ^0.2.1
  package_info_plus: ^4.0.2
  
  # downloads screen
  file_picker: ^5.3.0
  permission_handler: ^10.2.0
  
  # for video player
  video_player: ^2.6.1
  flutter_screen_wake: ^1.0.2
  screen_brightness: ^0.2.2
  perfect_volume_control: ^1.0.5
  webview_flutter: ^3.0.4
  html: ^0.15.4
  http: ^0.13.6

flutter_native_splash:
  background_image: 'assets/splash.png'
  fullscreen: true
  android: true
  ios: true

flutter_launcher_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/home.png
    - assets/search.png
    - assets/settings.png
    - assets/download.png
    - assets/bookmark.png
    - assets/backward.png
    - assets/forward.png
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700